### PR TITLE
Sl peanutshell

### PR DESCRIPTION
**Pull request by sophialawesome**
1. git fetch --all
2. git checkout sl-peanutshell

Test to see if the login works. The code should validate a user's input - if the user already exists, the console will display a welcome message ("Hello, ${user}"). If the credentials are incorrect or the user doesn't exist in the database, an error message will display.

### CODE REVIEW

**Comment by fimoefive** [comment]
Your code looks good!

**Comment by ZachRoark** [comment]
looks good

**Comment by wildwes** [comment]
it gives me the following error:
"main.js:27 Uncaught (in promise) TypeError: Cannot read property 'id' of undefined
    at main.js:27
(anonymous) @ main.js:27
Promise.then (async)
(anonymous) @ main.js:12"

**Comment by wildwes** [comment]
Great job!

**Pull request merged**
